// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtHO1n73xa4CsY_tEgl99D2KokEBjhUpk',
    appId: '1:717221513144:web:bc6511b537e96c885a714d',
    messagingSenderId: '717221513144',
    projectId: 'air-line-7c9ce',
    authDomain: 'air-line-7c9ce.firebaseapp.com',
    storageBucket: 'air-line-7c9ce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJJXItrnseF7RvMhPQPu8wo1Rdy9zhsa0',
    appId: '1:717221513144:android:6d39c45f71c1635e5a714d',
    messagingSenderId: '717221513144',
    projectId: 'air-line-7c9ce',
    storageBucket: 'air-line-7c9ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGEfxaC8g7MaGvk1Jhj5Q56MduKO5owXo',
    appId: '1:717221513144:ios:294e6fd7650055505a714d',
    messagingSenderId: '717221513144',
    projectId: 'air-line-7c9ce',
    storageBucket: 'air-line-7c9ce.appspot.com',
    iosBundleId: 'com.example.flowerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGEfxaC8g7MaGvk1Jhj5Q56MduKO5owXo',
    appId: '1:717221513144:ios:294e6fd7650055505a714d',
    messagingSenderId: '717221513144',
    projectId: 'air-line-7c9ce',
    storageBucket: 'air-line-7c9ce.appspot.com',
    iosBundleId: 'com.example.flowerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtHO1n73xa4CsY_tEgl99D2KokEBjhUpk',
    appId: '1:717221513144:web:6c68e85499123b0a5a714d',
    messagingSenderId: '717221513144',
    projectId: 'air-line-7c9ce',
    authDomain: 'air-line-7c9ce.firebaseapp.com',
    storageBucket: 'air-line-7c9ce.appspot.com',
  );
}
